install:
  - cd src
  - make -f makefile.unix
   
language: cpp
 
before_install:
  - sudo apt-get install libssl-dev libdb5.1++-dev libboost-all-dev libminiupnpc-dev -y

branches:
  only:
    - master
