install:
  - cd src
  - make -f makefile.unix
   
language: cpp
 
before_install:
  - sudo apt-cache search libdb | grep "++-dev"
  - sudo apt-get install libssl-dev libdb4.8++-dev libboost-all-dev libminiupnpc-dev -y

branches:
  only:
    - master
